project_id = "bpjzgapmoyhtgryglcke"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["http://localhost:5173"]
jwt_expiry = 3600

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[functions.admin-file-manager]

[functions.create-user]

[functions.delete-user]

[functions.flexi-connect]

[functions.get-all-users]

[functions.get-file-metadata]

[functions.get-subscription]
verify_jwt = false

[functions.list-version-files]

[functions.voice-recording-webhook]

[functions.klinika-admin]

[functions.invitation-handler]
verify_jwt = false

[functions.szabalyok-webhook]

[functions.extraction-callback]
verify_jwt = false

[functions.szotar-rules-webhook]
verify_jwt = false

[functions.szotar-callback]
verify_jwt = false

[functions.generate-szotar-embeddings]

[functions.regenerate-rule-embedding]
