-- Insert first batch of BNO codes (first 100)
INSERT INTO bno_codes (code, name) VALUES
('A0000', 'Cholera (Vibrio cholerae 01, cholera biovariáns okozta)'),
('A0010', 'Cholera (Vibrio cholerae 01, El Tor biovariáns okozta)'),
('A0090', 'Cholera k.m.n.'),
('A0100', 'Hastyphus'),
('A0110', 'Paratyphus "A"'),
('A0120', 'Paratyphus "B"'),
('A0130', 'Paratyphus "C"'),
('A0140', 'Paratyphus k.m.n.'),
('A0200', 'Salmonella bélhurut'),
('A0210', 'Salmonella sepsis'),
('A0220', 'Salmonella helyi fertïzések'),
('A0280', 'Egyéb meghatározott salmonella fertïzések'),
('A0290', 'Salmonella fertïzés k.m.n.'),
('A0300', 'Shigellosis, Shigella dysenteriae okozta'),
('A0310', 'Shigellosis Shigella flexneri miatt'),
('A0320', 'Shigellosis, Shigella boydii miatt'),
('A0330', 'Shigellosis, Shigella sonnei miatt'),
('A0380', 'Egyéb shigellosis'),
('A0390', 'Shigellosis k.m.n.'),
('A0400', 'Enteropathogen Escherichia coli fertïzés'),
('A0410', 'Enterotoxikus Escherichia coli fertïzés'),
('A0420', 'Enteroinvasiv Escherichia coli fertïzés'),
('A0430', 'Enterohaemorrhagiás Escherichia coli fertïzés'),
('A0440', 'Escherichia coli enteritis, k.m.n.'),
('A0450', 'Campylobacter okozta bélhurut'),
('A0460', 'Yersinia enterocolitica okozta bélhurut'),
('A0470', 'Clostridium difficile okozta vékony- és vastagbélgyulladás'),
('A0480', 'Egyéb meghatározott baktériumok által okozott bélfertïzések'),
('A0490', 'Baktériumok által okozott bélfertïzés k.m.n.'),
('A0500', 'Staphylococcus által okozott ételmérgezés'),
('A0510', 'Botulizmus'),
('A0520', 'Clostridium perfringens [Clostridium welchii] okozta ételmérgezés'),
('A0530', 'Vibrio parahaemolyticus ételmérgezés'),
('A0540', 'Bacillus cereus ételmérgezés'),
('A0580', 'Egyéb meghatározott baktériumok által okozott ételmérgezések'),
('A0590', 'Bakteriális ételmérgezés, k.m.n.'),
('A0600', 'Heveny amoebás dysenteria'),
('A0610', 'Idült bél amoebiasis'),
('A0620', 'Amoebás vastagbélgyulladás, nem vérhassal járó'),
('A0630', 'Bél amoeboma'),
('A0640', 'Amoebás májtályog'),
('A0650', 'Amoebás tüdïtályog (J99.8*)'),
('A0660', 'Amoebás agytályog (G07*)'),
('A0670', 'Bïr amoebiasis'),
('A0680', 'Egyéb lokalizációjú amoebás fertïzés'),
('A0690', 'Amoebiasis k.m.n.'),
('A0700', 'Balantidiasis'),
('A0710', 'Giardiasis [lambliasis]'),
('A0720', 'Cryptosporidiosis'),
('A0730', 'Isosporosis'),
('A0780', 'Egyéb meghatározott protozoon bélbetegségek'),
('A0790', 'Protozoon bélbetegség k.m.n.'),
('A0800', 'Rotavirus bélhurut'),
('A0810', 'Norwalk-ágens által okozott heveny gyomor-bélbetegség'),
('A0820', 'Adenovirus okozta bélhurut'),
('A0830', 'Egyéb vírusos bélhurut'),
('A0840', 'Vírusos bélfertïzés k.m.n.'),
('A0850', 'Egyéb meghatározott bélfertïzések'),
('A09H0', 'Feltételezetten fertïzï eredet¹ hasmenés és gyomor-bélhurut')
ON CONFLICT (code) DO NOTHING;